In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [16]:
caminho_arquivo = r'C:\Users\bernardo_b_garcia\Downloads\clientes_compra_misterio.xlsx'
df_compra = pd.read_excel(caminho_arquivo)

In [17]:
df_compra.columns = ['tempo_gasto_site', 'numero_itens_visualizados','compras_anteriores']

In [18]:
mapeamento_compras_anteriores = {'Sim':0, 'NÃ£o':1}

In [19]:
df_compra['compras_anteriores'] = df_compra['compras_anteriores'].map(mapeamento_compras_anteriores)

In [20]:
df_compra

    tempo_gasto_site  numero_itens_visualizados  compras_anteriores
0                 10                          5                   1
1                 15                          7                   0
2                 20                          8                   0
3                  5                          3                   1
4                 25                         10                   0
5                 30                         12                   0
6                  8                          4                   1
7                 12                          6                   0
8                 18                          9                   0
9                  7                          3                   1
10                22                         11                   0
11                28                         13                   0
12                 6                          2                   1
13                14                          7                   0
14                16                          8                   0
15                 9                          4                   1
16                24                         10                   0
17                32                         14                   0